theme: jekyll-theme-cayman
title: Florence
description: Business Analytics Projects | Tableau, Power BI, Python, SQL, VBA
description: Business Domains | Banking, Payment, Wealth Management, Consulting
